apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer 
# reclaim Policy can be Retain or Delete , by default its delete, if reclaim policy is retain ,
# PV that are dynamically created for this SC will have the reclaim policy of storage class
reclaimPolicy: Retain
allowVolumeExpansion: true


# STORAGE CLASS 
# 1. A StorageClass provides a way for administrators 
# to describe the "classes" of storage they offer.
# 2. Here we are offering EBS Storage for EKS Cluster